### ISSUE TITLE
Create a Helm Chart that uses the ECK operator to create a ES Cluster

### ISSUE THREAD

**Issue by operatorequals** [operatorequals/Blue-Baron#1]
A basic Helm chart is to be created to add basic templating on `Elasticsearch` and `Kibana` CRDs of Elastic Operator.

Specifically a multi-`NodeSet` templating as below can be used for `ElasticSearch`:
```yaml
elasticsearch:
  name: cluster-name
  version: 7.9.0
  nodeSets:
    - name: nset1
      mmap: 
        vm_max_map_count: 262144
        enabled: false
      roles:
        - "master"
        - "data"
        - "ingest"
      limits:
        cpu: 1
        memory: 1Gi
      heapSize: 512m  # Use [m for Megabytes, g for gigabytes]
      count: 1
      volumeClaims:
        class: standard
        size: 1Gi
  service:
    enabled: true
    type: LoadBalancer
    # name: elastisearch
```
