### ISSUE TITLE
Elastic-cluster Helm Chart ingresses

### ISSUE THREAD

**Issue by operatorequals** [operatorequals/Blue-Baron#9]
The `elastic-cluster` Helm Chart does not have any definition for Ingresses. As it deploys a Kibana and ES instance with separate ClusterIP services, it would be useful to include an Ingress YAML definition in the `values.yaml` file for each of the components ( Kibana and ES ).

This way, there will be no need to externally create K8s resources to support the deployment of the ES cluster.

The Ingress YAML definition could be exactly like the default one:
```yaml
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kibana.example.com
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

but inside `kibana` or `elasticsearch` blocks (e.g `kibana.ingress`, `elasticsearch.ingress`).
It can also use the TLS secrets generated by ECK directly as default, while also giving the user the opportunity to deploy their own TLS secrets.
